# Introduction

When I was a high-school student, biology was my favourite subject. My bigger brother used the same textbook in a outline edition and thus I didn't need to buy it. Meanwhile my classmates were using the newer edition, I enjoyed reading the old edition from my brother. That book had over 1000 pages and was completely in black and white. Students and teachers alike spotted me reading that book almost all the time at the corner of the spectator stand.

# A Whole game

Get the readers' hands dirty with a simple example. Give a sense of what a typical ACA scenerio looks like. And use that in the next chapter to illustrate the best practice.

# From theory to ACA, back to theory
## Content analysis

As a super express summary of Krippendorff and Neuendorf. But don't do it like Leetaru!

## Automated content analysis

What the current literature says about ACA.

## Best practice

* Validation
* Confirmatory / exploratory
* Methodological transparency

# Creating gold standard & validation

* avocate a workflow of making gold standard first!

# Typical automated content analytic methods
## dictionary-based method

* how it works
* off-the-shelf
* creating domain specific one

### validation

* suggestions

## topic-model

### validation

* daniel maier / Chang

# Advance topics
## bag-of-embeddings
## semantic network
## machine learning
## multimodal analysis
## crosslingual analysis
